language: node_js

node_js:
    - "8.0.0"

env:
    global:
        - NODE_ENV=test

dist: trusty

cache:
    yarn: true
    directories:
        - node_modules

before_install:
    - npm install -g yarn

install:
    - yarn
    - make --silent install

before_script:
  - git checkout master
  - lerna updated --json
script:
  - lerna run test --since master #This always runs all packages even if only one was changed
  - lerna publish -m "bump versions [ci skip]" --conventional-commits --yes
after_script:
  - git push
